# Site settings
title: JFMDev
email: kudalab@inboxalias.com
description: > # this means to ignore newlines until "baseurl:"
  Personal code lab of web, mobile and open source software
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jfmdev.github.io" # the base hostname & protocol for your site
twitter_username: ""
github_username: jfmdev

# Compress SASS
sass:
    style: :compressed

# Build settings
markdown: kramdown
